# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries
version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-upload:
    executor: python/default
    environment:
      TWINE_USERNAME: $PYPI_USERNAME
      TWINE_PASSWORD: $PYPI_PASSWORD
    steps:
      - checkout
      - run:
          command: |
            python -m pip install --upgrade pip
            pip install setuptools wheel twine
            python setup.py sdist bdist_wheel
            twine upload dist/*

workflows:
  main:
    jobs:
      - build-and-upload