version: 2.1


jobs:
  build:
    docker:
      - image: python:3.8
    
    working_directory: ~/repo  

    environment:
      TWINE_USERNAME: $PYPI_USERNAME
      TWINE_PASSWORD: $PYPI_PASSWORD
    
    steps:
      - checkout

      - run:
          name: Install packages
          command: |
            python3 -m venv convenv
            . convenv/bin/activate
            python -m pip install --upgrade pip
            pip install setuptools wheel twine
            pip freeze > requirements.txt

      - save_cache:
          key: $CIRCLE_SHA1
          paths:
            - "~/repo/requirements.txt"
      
      
  upload:
    docker:
      - image: python:3.8
    
    working_directory: ~/repo

    environment:
      TWINE_USERNAME: $PYPI_USERNAME
      TWINE_PASSWORD: $PYPI_PASSWORD
    
    steps:
      - restore_cache:
          key: $CIRCLE_SHA1
          paths:
            - "~/repo/requirements.txt"    

      - run:
          name: Upload Package
          command: |
            python3 -m venv convenv
            . convenv/bin/activate
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            python setup.py sdist bdist_wheel            
            twine upload dist/*

workflows:
  build_and_upload:
    jobs:
      - build
      - upload:
          requires:
            - build
