version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    
    steps:
      - checkout
      
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "setup.py" }}
      
      - run:
          name: Install Python Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python -m pip install --upgrade pip
            pip install setuptools wheel twine

      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "setup.py" }}
          paths:
            - "venv"

      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = $PYPI_USERNAME" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc

      - run:
          name: Create Packages
          command: |
            python setup.py sdist bdist_wheel
      - run:
          name: Upload to PyPi
          command: |
            . venv/bin/activate
            twine upload dist/*

workflows:
  build_and_deploy:
    jobs:
      - build