version: 2.1

jobs:
  build:
    docker:
      - image: python:3.8
    
    steps:
      - checkout

      - run:
          name: Install packages
          command: |
            python3 -m venv convenv
            . convenv/bin/activate
            python -m pip install --upgrade pip
            pip install setuptools wheel twine

      - save_cache:
          paths:
            - "convenv"
      
      
  upload:
    - environment:
      TWINE_USERNAME: $PYPI_USERNAME
      TWINE_PASSWORD: $PYPI_PASSWORD
    
    - restore_cache:
        paths:
          - "convvenv"    
    
    - run:
        name: Upload Package
        command: |
          . convenv/bin/activate
          python setup.py sdist bdist_wheel
          twine upload dist/*

workflows:
  build_and_upload:
    jobs:
      - build
      - upload:
          requires:
            - build