version: 2.1

jobs:      
  upload:
    docker:
      - image: python:3.8
    
    working_directory: ~/repo

    environment:
      TWINE_USERNAME: $PYPI_USERNAME
      TWINE_PASSWORD: $PYPI_PASSWORD
    
    steps:
      - run:
          name: Upload Package
          command: |
            python3 -m venv convenv
            . convenv/bin/activate
            python -m pip install --upgrade pip
            pip install setuptools wheel twine
            python setup.py sdist bdist_wheel            
            twine upload dist/*

workflows:
  build_and_upload:
    jobs:
      - upload